export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const SESSION_TOKEN_SERVICE = Symbol('SESSION_TOKEN_SERVICE');
export const LOGIN_RATE_LIMITER = Symbol('LOGIN_RATE_LIMITER');
export const SECURITY_AUDIT_SERVICE = Symbol('SECURITY_AUDIT_SERVICE');
