export const SCHEDULING_ENGINE = Symbol('SCHEDULING_ENGINE');
export const SCHEDULING_DAY_POLICY = Symbol('SCHEDULING_DAY_POLICY');
export const SCHEDULING_CAPACITY_POLICY = Symbol('SCHEDULING_CAPACITY_POLICY');
export const CANDIDATE_GENERATOR = Symbol('CANDIDATE_GENERATOR');
export const SCHEDULE_REPOSITORY = Symbol('SCHEDULE_REPOSITORY');
export const SCHEDULING_PROPOSAL_REPOSITORY = Symbol('SCHEDULING_PROPOSAL_REPOSITORY');

